### ISSUE TITLE
Please allow PHPUnit 7.x or 8x

### ISSUE THREAD

**Issue by mimmi20** [endorphin-studio/browser-detector-tests#2]
Here PHPUnit 6.5 is used. For PHP 7.1 PHPUnit 7.5 is available, for PHP 7.2+ PHPUnit 8.x is available.

**Comment by serhiime** [comment]
PHP 7.4, 7.3, 7.2
./vendor/bin/phpunit -c ./vendor/endorphin-studio/browser-detector-tests/phpunit.xml.dist

Fatal error: Declaration of EndorphinStudio\Tests\TestBase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /var/www/html/vendor/endorphin-studio/browser-detector-tests/src/TestBase.php on line 26

**Comment by mimmi20** [comment]
> Fatal error: Declaration of EndorphinStudio

Do you really still need PHP 7.0? If you would drop this version, it would be easy to fix

**Comment by serhiime** [comment]
@mimmi20 I want to maintain all version since 7.0 but It will probably need to separate versions

**Comment by serhiime** [comment]
I will work on this at this week

**Comment by serhiime** [comment]
@mimmi20 PHPUnit 9.x was added in 3.1 Release: https://github.com/endorphin-studio/browser-detector-tests/releases/tag/3.1
